### ISSUE TITLE
Figure 6.1 seems to be missing

### ISSUE THREAD

**Issue by ShadowJonathan** [SoarGroup/SoarGroup.github.io#16]
I'm not sure if more figures are missing, but when reading https://soar.eecs.umich.edu/soar_manual/06_SemanticMemory/, I noticed that figure 6.1 was not visible at all on the website while it is visible in the PDF

**Comment by garfieldnate** [comment]
Thanks very much for reporting! I've added a comment to #13, where I plan to track issues related to the PDF/website mismatch. The entire tutorial and manual need to be reviewed before we can remove the big "Under Construction" banner.

I'm closing this here, but will continue to track in #13.
