### ISSUE TITLE
Add workshop section

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/SoarGroup.github.io#19]
Add a new workshop section to collect schedules and materials for all workshops. We can start by adding the materials collected this year!

Related: #11, #17

**Comment by moschmdt** [comment]
The [blog feature](https://squidfunk.github.io/mkdocs-material/blog/) could be interesting for this? I currently think of one blog entry per presentation and tag it with the edition of the corresponding Soar workshop?

**Comment by garfieldnate** [comment]
I'm not so sure that a blog structure is the right fit here; I want to have a single page per year with the full schedule listed, along with all relevant links (videos, transcripts, slides). The blog feature would kind of spread this information out, right? Also the RSS feed would immediately be filled with all the workshop presentations, then likely not have activity until the next workshop.

If we were to use the blog feature, I think I would like better the idea of applying it to the announcement section. Having a new blog post for each bit of news, including new publications, would I think fit better. Then one post would contain a pointer to the workshop proceedings, and that would appear in your RSS feed.

What do you think?

**Comment by moschmdt** [comment]
I am totally fine with your suggestion! I think what you describe is something similar to what ROS does for their ROSCon talks in their [docs](https://docs.ros.org/en/rolling/The-ROS2-Project/ROSCon-Content.html). 

I just wanted to point out the possibility of the blog. Did not think about the announcements, though. This actually sounds like a good use case!

**Comment by garfieldnate** [comment]
That is a really great reference, thank you! Something similar would be great.
