### ISSUE TITLE
WIP Warning disables table of contents for manual and tutorials

### ISSUE THREAD

**Issue by moschmdt** [SoarGroup/SoarGroup.github.io#21]
Just noticed that the WIP warning for the Soar manual and the Soar tutorials somehow disables the 
table of contents column on the right-hand side.

**Comment by garfieldnate** [comment]
Thanks for the heads-up! I'm not sure it's urgent, since it will get fixed when the manual/tutorial are accepted, but it's very good to know.

**Comment by analog-cbarber** [comment]
I don't think this is due to the warning. I think the issue is that the subpages must not have an H1 title in order to be included in the ToC. Basically, just add an extra `#` to every header.

I will contribute a fix.
