### ISSUE TITLE
Where is "Soar XML Interface Specification"

### ISSUE THREAD

**Issue by analog-cbarber** [SoarGroup/SoarGroup.github.io#34]
The [SML Quick Start Guide](https://soar.eecs.umich.edu/tutorials/SMLQuickStartGuide/#sml-quick-start-guide)
refers to the "Soar XML Interface Specification", but I could not find that anywhere.

Could you add that to the documentation or at least provide a pointer to where it actually lives?

**Comment by garfieldnate** [comment]
Thanks for finding this! I'm actually just going to remove that reference from the documentation for now, since it's not relevant for users of the SML API and it may take some real sleuthing to track down that document. 😄

I'll ask around and see if we can locate it, though.

**Comment by garfieldnate** [comment]
All fixed. Thanks again @analog-cbarber for finding this!

**Comment by analog-cbarber** [comment]
Still would be nice to see the spec. Ideally communication protocol specs should not only be implicit in an API.

**Comment by garfieldnate** [comment]
@analog-cbarber No worries, it's been added to the website. It's linked on the page you were reading.
